version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: twitter-postgres
    hostname: postgres
    ports:
      - 5432:5432
    user: postgres 
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: twitter

